[package]
name = "grepper"
version = "0.1.0"
authors = ["ana <ana@altonotch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

structopt = "0.2.10"
chrono = "0.4.10"
serde = "1.0.103"
serde_json = "1.0.44"
